blog/app/urls.py
from django.urls import path,include
from django.urls.conf import re_path
from .import views

app_name = "app"

urlpatterns = [
    path('',views.Article_list,name="article"),
    path('',views.Base,name="Base"),
    path('',views.Home,name="Home"),
    path('accounts/login/',views.Login,name="Login"),
    path('accounts/signup/',views.SignUp,name="SignUp"),
    path('logout',views.handleLogout,name="handleLogout"),
    path('contact',views.Contact,name="Contact"),
    path('article',views.Add_article,name="Add_article"),
    re_path('article-read/(?P<slug>[\w-]+)',views.Article_detail,name="detail"),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Contacts(models.Model):
    name = models.CharField(max_length=50)
    email =models.EmailField()
    message =models.TextField()

    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:100]+"..."

blog/app/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body' , 'thumb',]

blog/app/views.py
from django.shortcuts import redirect, render,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Contacts,Article
from .import forms

# Create your views here.
def Base(request):
    return render(request,"home.html")

def Home(request):
    return render(request,"home.html")
    
def Contact(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        msg = request.POST.get("message")
        myquery = Contacts(name =name,email=email,message=msg)
        myquery.save()
        messages.info(request,"Thanks for contacting,we will get back to you soon")
        return redirect('/')
    return render(request,"contact.html")

def Article_detail(request,slug):
    article = Article.objects.get(id=slug)
    return render(request,'article_detail.html',{'article':article})

@login_required(login_url="/accounts/login/")
def Add_article(request):
    if request.method=="POST":
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            messages.info(request,"Thanks for Adding Article .")
            return redirect('/')
    else:
        form = forms.CreateArticle()
    return render(request,"create_article.html",{ 'form': form })


def Article_list(request):
    article = Article.objects.all().order_by('date')
    return render(request,'articles_list.html',{'articles':article})

def Login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        myuser = authenticate(username=username,password=password)
        if myuser is not None:
            login(request,myuser)
            messages.success(request,"login Successfull")
            return redirect('/')
        else:
            messages.error(request,"Invalid Credentials")
    return render(request,"login.html")

def SignUp(request):
    if request.method == "POST":
        username=request.POST.get('username')
        firstname=request.POST.get('fname')
        lastname=request.POST.get('lname')
        email=request.POST.get('email')
        pass1=request.POST.get('password1')
        pass2=request.POST.get('password2')
        print(firstname)
        if pass1!=pass2:
            messages.info(request,"Password is not Matching")
            return redirect('/accounts/signup/')
        try:
            if User.objects.get(username=username):
                messages.warning(request,"UserName is Taken")
                return redirect('/accounts/signup/')
        except Exception as identifier:
            pass
        try:
            if User.objects.get(email=email):
                messages.warning(request,"Email is Taken")
                return redirect('/accounts/signup/')
        except Exception as identifier:
            pass
        myuser = User.objects.create_user(username,email,pass1)
        myuser.first_name = firstname
        myuser.last_name = lastname
        myuser.save()
        messages.success(request,"User is Created Please Login")
        return redirect('/accounts/login/')
    return render(request,"signup.html")

def handleLogout(request):
    logout(request)
    messages.success(request,"Logout Success")    
    return redirect('/accounts/login/')

blog/templates/article_detail.html
{% include "base.html" %}
<div class="container mt-5">
    <div class="row">
        <div class="col"></div>
        <div class="col-8 mb-5">
            <div class="card">
                <img class="card-img-top" src="{{article.thumb.url}}" alt="Card image cap">
                <div class="card-body">
                    <h2 class="card-title">{{article.title}}</h2>
                    <p class="card-text">{{article.body}}</p>
                    <h6>Author : {{article.author.username}}</h6>
                    <hr>
                    <p>Posted : {{article.date}}</p>
                </div>
            </div> 
        </div>
        <div class="col"></div>
    </div>
</div>
{% include 'footer.html' %}

blog/templates/articles_list.html
{% extends "home.html" %}
{% block article_list %}
<div class="container mt-5">
    <div class="row">
    {% for article in articles %}
        <div class="col-md-4 mb-5 ">
            <div class="card">
                <img class="card-img-top " src="{{article.thumb.url}}" style="height: 230px;widht: 286px;" alt="Card image cap">
                <div class="card-body">
                    <h4 class="card-title">{{article.title}}</h4>
                    <p class="card-text">{{article.snippet}}</p>
                    <h6>Author : {{article.author.username}}</h6>
                    <hr>
                    <div class="row mb-0">
                    <div class="col-8"><p>Posted : {{article.date}}</p></div>
                    <div class="col"><a href="{% url 'app:detail' slug=article.id %}" class="btn btn-primary">Read More</a></div>
                    </div>
                    </div>    
            </div> 
        </div>
    {% endfor %}
    </div>
</div>
{% endblock article_list %}

blog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'css/favicon.ico' %}" />
    <title>Blogify</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg">
      <div class="container-fluid">
        <div class="mx-4 flex-row">
          <div class="d-flex flex-column">
            <a class="navbar-brand " id="brand" href="/">Blogify</a>
            {% comment %} <a class="navbar-brand pt-0"  id="sub_brand" href="#">The Taste of Home</a> {% endcomment %}
          </div>
        </div>
        
        <div class="mx-4">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="d-flex ms-auto justify-content-center">
                  <ul class=" navbar-nav mb-2 my-lg-2 ">
                    <li class="nav-item mx-3 nav_section">
                      <a class="nav-link" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item mx-3 nav_section">
                      <a class="nav-link" href="/article">Add Article</a>
                    </li>
                    <li class="nav-item mx-3 nav_section">
                      <a class="nav-link" href="/contact">Contact Us</a>
                    </li>

                    {% if not request.user.is_authenticated %}
                      <li class="nav-item mx-3 nav_section">
                        <a class="nav-link" href="/accounts/login/">Log in</a>
                      </li>
                      <li class="nav-item mx-3 nav_section">
                        <a class="nav-link" href="/accounts/signup/">Sign up</a>
                      </li>
                    {% else %}
                      <li class="nav-item dropdown nav_section">
                        <a class="nav-link dropdown-toggle "  href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Welcome {{user.username}}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown"><strong></strong>
                            <li><a class="dropdown-item" href="/logout" ><b>Logout</b></a></li>
                        </ul>
                      </li>
                    {% endif %}
                  </ul>
            </div>
          </div>
      </div>
    </nav>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  
  </body>
</html>

blog/templates/contact.html
{% include "base.html" %}
<div class="row">
<div class="col"></div>
<div class="col-lg-6 mt-5" style="padding:0px 50px 50px 50px;">
<form action="/contact" method="post">{% csrf_token %}
  <h2>Contact Details</h2>
  <div class="form-row">
    <div class="form-group mt-3 mb-3">
      <h5><label for="name" class="my-1">Name</label></h5>
      <input type="text" class="form-control" id="name" name="name" placeholder="Your Name" required>
    </div>
    <div class="form-group mb-3">
      <h5><label for="inputEmail4" class="my-1">Email</label></h5>
      <input type="email" class="form-control input-lg" id="inputEmail4" name="email" placeholder="example@gmail.com" required>
    </div>
  </div>
  <div class="form-group mb-3">
    <h5><label for="comment" class="my-1">Message</label></h5>
    <textarea class="form-control" rows="5" id="comment" name="message" required></textarea>
  </div>
  <button type="submit" class="btn btn-primary btn-lg">Submit</button>
</form> 
</div>
<div class="col"></div>
</div>

blog/templates/create_article.html
{% include "base.html" %}
    <div class="row">
      <div class="col mt-4" ></div>
      <div class="col-lg-6 mt-4" style="padding:0px 50px 50px 50px;">
      <form action="{% url 'app:Add_article' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
          <h2>Write your Article</h2>
        <div class="form-row">
          <div class="form-group mt-2 mb-3">
            <h5><label for="{{form.id_title}}" class="my-1">Title :</label></h5>
            <input type="text" class="form-control" id="{{form.id_title}}" name="title" placeholder="Your Name" required>
          </div>
        </div>
        <div class="form-group mb-3">
          <h5><label for="{{form.id_body}}" class="my-1">Body :</label></h5>
          <textarea class="form-control" rows="8" id="{{form.id_body}}" name="body" required></textarea>
        </div>
        <div class="form-group mb-3">
          <h5><label class="form-label" for="{{form.id_thumb}}">Upload Image</label><h5>
          <input type="file" class="form-control" name="thumb" accept="image/*" id="{{form.id_thumb}}" />
        </div>
        <button type="submit" class="btn btn-primary btn-lg">Create</button>
      </form> 
      </div>
      <div class="col mt-4"></div>
    </div> 

blog/templates/footer.html
<footer class="footer">
  <div class="text-center text-white" style="background-color: #4590f3;">

  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-2">

      <!-- Linkedin -->
        <a href="https://www.linkedin.com/in/harsh-balpande/" class="text-white">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16" style="margin-right:15px;">
            <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
        </svg>
        </a>

      <!-- Github -->
        <a href="https://github.com/harshbalpande55" class="text-white">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
        </svg>
        </a>

      <!-- Facebook -->
        <a href="https://www.facebook.com/harshbalpande55" class="text-white">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16" style="margin-left:15px;">
            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
        </svg>
        </a>

    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-white p-3" style="background-color:#4590f3;">
    © 2021 Copyright:
    <a class="text-white" href="https://harshbalpande55.github.io/cv/">Harsh Balpande</a>
  </div>
  <!-- Copyright -->
</div>
</footer>

blog/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blogify</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    <link rel="shortcut icon" href="{% static 'css/favicon.ico' %}" />
</head>
<body>
    {% include "base.html" %}
    {% for message  in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
    {% block article_list %}{% endblock article_list %}
    {% include "footer.html" %}
</body>
</html>

blog/templates/login.html
{% load static %}
{% load socialaccount %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <title>Blogify</title>
    <link rel="shortcut icon" href="{% static 'css/favicon.ico' %}" />
  </head>
  <body>
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col-lg-4 mid">
                <main class="form-signin">
                <a class="navbar-brand " id="brand" href="/">Blogify</a>
                <h1 class="h3 mb-3 fw-normal">Log in</h1>
                <br>
                <div class="d-grid gap-2">
                <a  class="btn btn-light"  href="{% provider_login_url 'google' %}">Login With <img src="https://img.icons8.com/color/30/000000/google-logo.png"/></a>
                </div>

                <p class="text-center mt-3 text-success">OR</p>
                    {% for message  in messages %}
                    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                      <strong></strong> {{message}}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                
                <form action="/accounts/login/" method="post">{% csrf_token %}
                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="floatingInput" name="username" placeholder="UserName" required>
                        <label for="floatingInput">UserName</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password" required>
                        <label for="floatingPassword">Password</label>
                    </div>
                    <button class="w-100 btn btn-lg btn-warning" type="submit">log in</button>
                    <div class="redirect_signup"><strong><a href="/accounts/signup/">New User?</a></strong></div>
                    <p class="mt-3 mb-0 text-dark">&copy; 2021–Harsh Balpande</p>
                </form>
                </main>
            </div>
            <div class="col"></div>
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

blog/templates/signup.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
    <title>Blogify</title>
    <link rel="shortcut icon" href="{% static 'css/favicon.ico' %}" />
  </head>
  <body>
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col-lg-4 mid">
                <main class="form-signin">
                <a class="navbar-brand " id="brand" href="/" >Blogify</a>
                <h1 class="h3 mb-3 fw-normal">Sign up</h1>
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                        <strong></strong> {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
                <form action="/accounts/signup/" method="post">{% csrf_token %}
                    <div class="form-floating mb-2">
                        <input type="text" class="form-control" id="floatingInput" name="username" placeholder="UserName" required>
                        <label for="floatingInput">UserName</label>
                    </div>
                    <div class="form-floating mb-2">
                        <input type="text" class="form-control" id="floatingInput" name="fname" placeholder="fName" required>
                        <label for="floatingInput">FirstName</label>
                    </div>
                    <div class="form-floating mb-2">
                        <input type="text" class="form-control" id="floatingInput" name="lname" placeholder="lName" required>
                        <label for="floatingInput">LastName</label>
                    </div>
                    <div class="form-floating mb-2">
                        <input type="email" class="form-control" id="floatingInput" name="email" placeholder="UserName" required>
                        <label for="floatingInput">Email address</label>
                    </div>
                    <div class="form-floating mb-2">
                        <input type="password" class="form-control" id="floatingPassword" name="password1" placeholder="Password1" required>
                        <label for="floatingPassword">Password</label>
                    </div>
                    <div class="form-floating mb-2">
                        <input type="password" class="form-control" id="floatingPassword" name="password2" placeholder="Password2" required>
                        <label for="floatingPassword">Confirm Password</label>
                    </div>
                    <button class="w-100 btn btn-lg btn-warning" type="submit">Sign up</button>
                    <div class="redirect_signup"><strong><a href="/accounts/login/">Already User?</a></strong></div>
                    <p class="mt-3 mb-0 text-dark">&copy; 2021–Harsh Balpande</p>
                </form>
                </main>
            </div>
            <div class="col"></div>
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>